version: '2'

services:
  echolotio:
    image: mablanco/bolt-cms:3.7.2
    ports:
      - "9000:80"
    environment:
      - BOLT_TITLE=Echolot.io
    volumes:
      - ./db-data:/var/www/html/app/database
      - ./files:/var/www/html/public/files
      - ./config:/var/www/html/app/config
      - ./theme:/var/www/html/public/theme/echolotio